/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{vue,js,ts,jsx,tsx}",
  ],
  theme: {
    extend: {
      colors: {
        'css-primary': '#007bff',
        'css-secondary': '#6c757d',
        'css-accent': '#28a745',
      }
    },
  },
  plugins: [require('daisyui')],
  daisyui: {
    themes: [
      {
        'css-light': {
          'primary': '#007bff',
          'secondary': '#6c757d',
          'accent': '#28a745',
          'neutral': '#f8f9fa',
          'base-100': '#ffffff',
          'base-200': '#f8f9fa',
          'base-300': '#e9ecef',
          'info': '#17a2b8',
          'success': '#28a745',
          'warning': '#ffc107',
          'error': '#dc3545',
        },
        'css-dark': {
          'primary': '#0d6efd',
          'secondary': '#6c757d',
          'accent': '#198754',
          'neutral': '#212529',
          'base-100': '#1a1a1a',
          'base-200': '#2d2d2d',
          'base-300': '#404040',
          'info': '#0dcaf0',
          'success': '#198754',
          'warning': '#ffc107',
          'error': '#dc3545',
        },

        afterdark: {
          "primary": "#7B79B5",
          "secondary": "#ACABD5",
          "accent": "#fef3c7",
          "neutral": "#38357F",
          "base-100": "#201D65",
          "info": "#7dd3fc",
          "success": "#a7f3d0",
          "warning": "#fef08a",
          "error": "#fca5a5",
        },
        her: {
          "primary": "#b57979",
          "secondary": "#d5abab",
          "accent": "#fef3c7",
          "neutral": "#7f3535",
          "base-100": "#651d1d",
          "info": "#7dd3fc",
          "success": "#a7f3d0",
          "warning": "#fef08a",
          "error": "#fca5a5",
        },
        forest: {
          "primary": "#4ade80",
          "secondary": "#86efac",
          "accent": "#fef3c7",
          "neutral": "#166534",
          "base-100": "#052e16",
          "info": "#7dd3fc",
          "success": "#a7f3d0",
          "warning": "#fef08a",
          "error": "#fca5a5",
        },
        sky: {
          "primary": "#38bdf8",
          "secondary": "#7dd3fc",
          "accent": "#fef3c7",
          "neutral": "#0c4a6e",
          "base-100": "#082f49",
          "info": "#7dd3fc",
          "success": "#a7f3d0",
          "warning": "#fef08a",
          "error": "#fca5a5",
        },
        clays: {
          "primary": "#d97706",
          "secondary": "#f59e0b",
          "accent": "#fef3c7",
          "neutral": "#92400e",
          "base-100": "#451a03",
          "info": "#7dd3fc",
          "success": "#a7f3d0",
          "warning": "#fef08a",
          "error": "#fca5a5",
        },
        stones: {
          "primary": "#6b7280",
          "secondary": "#9ca3af",
          "accent": "#fef3c7",
          "neutral": "#57534e",
          "base-100": "#292524",
          "info": "#7dd3fc",
          "success": "#a7f3d0",
          "warning": "#fef08a",
          "error": "#fca5a5",
        },

      },
      'lofi',
      'black',
      'light',
      'dark',
      'cupcake',
      'corporate',
    ],
    darkTheme: 'css-dark',
    base: true,
    styled: true,
    utils: true,
    prefix: '',
    logs: true,
    themeRoot: ':root',
  },
}