
image: docker:latest

stages:
  - check
  - build
  - push

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_TAG: $CI_REGISTRY_IMAGE:$CI_COMMIT_SHORT_SHA
  IMAGE_LATEST: $CI_REGISTRY_IMAGE:latest

# Frontend checks
frontend-check:
  stage: check
  image: node:20-alpine
  before_script:
    - cd frontend
    - npm ci
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend
    paths:
      - frontend/node_modules/
#  artifacts:
#    paths:
#      - frontend/dist/
#    expire_in: 1 hour
  only:
    - merge_requests
    - master
    - main


# Frontend checks
frontend-edge--check:
  stage: check
  image: node:20-alpine
  before_script:
    - cd frontend_edge
    - npm ci
  script:
    - npm run build
  cache:
    key: ${CI_COMMIT_REF_SLUG}-frontend
    paths:
      - frontend/node_modules/
  #  artifacts:
  #    paths:
  #      - frontend/dist/
  #    expire_in: 1 hour
  only:
    - merge_requests
    - master
    - main

# Server checks
server-check:
  stage: check
  image: rust:1.90.0
  before_script:
    - cd server
    - apt-get update && apt-get install -y libpq-dev cmake build-essential
  script:
    - cargo test --all
    # Uncomment when ready:
    # - cargo fmt --all -- --check
    # - cargo clippy --all-targets --all-features -- -D warnings
  cache:
    key: ${CI_COMMIT_REF_SLUG}-server
    paths:
      - server/target/
      - $CARGO_HOME/registry/
      - $CARGO_HOME/git/
  only:
    - merge_requests
    - master
    - main

# CLI checks
cli-check:
  stage: check
  image: rust:1.90.0
  before_script:
    - cd cli
  script:
    - cargo test --all
    # Uncomment when ready:
    # - cargo fmt --all -- --check
    # - cargo clippy --all-targets --all-features -- -D warnings
  cache:
    key: ${CI_COMMIT_REF_SLUG}-cli
    paths:
      - cli/target/
      - $CARGO_HOME/registry/
      - $CARGO_HOME/git/
  only:
    - merge_requests
    - master
    - main

# Edge checks
edge-check:
  stage: check
  image: rust:1.90.0
  before_script:
    - cd edge
    - apt-get update && apt-get install -y libpq-dev cmake build-essential
  script:
    - cargo test --all
    # Uncomment when ready:
    # - cargo fmt --all -- --check
    # - cargo clippy --all-targets --all-features -- -D warnings
  cache:
    key: ${CI_COMMIT_REF_SLUG}-cli
    paths:
      - cli/target/
      - $CARGO_HOME/registry/
      - $CARGO_HOME/git/
  only:
    - merge_requests
    - master
    - main

# Build Docker image
build-docker:
  retry: 1
  stage: build
  image:
    name: gcr.io/kaniko-project/executor:v1.23.2-debug
    entrypoint: [""]
  script:
    - echo "{\"auths\":{\"$CI_REGISTRY\":{\"username\":\"$CI_REGISTRY_USER\",\"password\":\"$CI_REGISTRY_PASSWORD\"}}}" > /kaniko/.docker/config.json
    - /kaniko/executor --force --context $CI_PROJECT_DIR --dockerfile $CI_PROJECT_DIR/Dockerfile --destination $CI_REGISTRY_IMAGE --registry-mirror us0.regi.kube.gmp.io


  dependencies:
    - frontend-check
    - server-check
    - cli-check
  only:
    - master