-- Create device-related tables and enums for the Space Server device management system

-- Create enum for device kind (Edge or Kiosk)
CREATE TYPE space_device_kind AS ENUM ('edge', 'kiosk');

-- Create enum for device platform
CREATE TYPE space_device_platform AS ENUM ('windows', 'linux', 'macos', 'other');

-- Create space_devices table
CREATE TABLE space_devices (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    name VARCHAR(255) NOT NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    deleted_at TIMESTAMPTZ,
    last_seen_at TIMESTAMPTZ,
    kind space_device_kind NOT NULL,
    mac_address VARCHAR(17) NOT NULL,
    software_version VARCHAR(50) NOT NULL,
    ipv4_address VARCHAR(15),
    ipv6_address VARCHAR(45),
    uptime BIGINT NOT NULL DEFAULT 0,
    platform space_device_platform NOT NULL
);

-- Create space_device_auth table
CREATE TABLE space_device_auth (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_id UUID NOT NULL REFERENCES space_devices(id) ON DELETE CASCADE,
    auth_token VARCHAR(255) NOT NULL UNIQUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Create space_device_auth_requests table (device invite codes)
CREATE TABLE space_device_auth_requests (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    device_code VARCHAR(32) NOT NULL UNIQUE,
    expires_at TIMESTAMPTZ NOT NULL,
    used_at TIMESTAMPTZ,
    created_by UUID REFERENCES users(id) ON DELETE SET NULL,
    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

-- Add indexes for performance
CREATE INDEX idx_space_devices_kind ON space_devices(kind);
CREATE INDEX idx_space_devices_deleted_at ON space_devices(deleted_at);
CREATE INDEX idx_space_devices_last_seen_at ON space_devices(last_seen_at);
CREATE INDEX idx_space_device_auth_device_id ON space_device_auth(device_id);
CREATE INDEX idx_space_device_auth_token ON space_device_auth(auth_token);
CREATE INDEX idx_space_device_auth_requests_code ON space_device_auth_requests(device_code);
CREATE INDEX idx_space_device_auth_requests_expires ON space_device_auth_requests(expires_at);

-- Add comments for documentation
COMMENT ON TABLE space_devices IS 'Edge and Kiosk devices registered with the Space Server';
COMMENT ON TABLE space_device_auth IS 'Authentication tokens for registered devices';
COMMENT ON TABLE space_device_auth_requests IS 'Device registration invite codes (8 emojis)';

COMMENT ON COLUMN space_devices.name IS 'Friendly name generated by device at startup';
COMMENT ON COLUMN space_devices.last_seen_at IS 'Last heartbeat timestamp';
COMMENT ON COLUMN space_devices.mac_address IS 'MAC address of the device network interface';
COMMENT ON COLUMN space_devices.software_version IS 'Version of the device software';
COMMENT ON COLUMN space_devices.uptime IS 'Device uptime in seconds';
COMMENT ON COLUMN space_device_auth.auth_token IS 'Token used for MQTT authentication';
COMMENT ON COLUMN space_device_auth_requests.device_code IS '8-emoji registration code';

-- Update audit_logs constraint to include device-related events
ALTER TABLE audit_logs DROP CONSTRAINT IF EXISTS audit_logs_event_type_check;

ALTER TABLE audit_logs ADD CONSTRAINT audit_logs_event_type_check 
CHECK (event_type IN (
    -- Original user-related events
    'user_registration', 
    'user_login', 
    'user_logout', 
    'user_role_change',
    'user_profile_update', 
    'user_password_change', 
    'user_activation',
    'user_deactivation', 
    'user_deletion', 
    'admin_config_reload',
    'failed_login_attempt',
    -- Training-related events
    'training_session_started',
    'training_session_completed',
    'training_step_created',
    'training_step_updated', 
    'training_step_deleted',
    'trainer_assigned',
    'trainer_removed',
    'instructor_certified',
    'instructor_revoked',
    -- Tool-related events
    'tool_access_granted',
    'tool_access_denied',
    'tool_activated',
    'tool_deactivated',
    'tool_usage_logged',
    -- Device-related events
    'device_invite_created',
    'device_invite_used',
    'device_invite_expired',
    'device_registered',
    'device_name_changed',
    'device_deleted',
    'device_version_changed'
));

-- Add index for device-related audit events
CREATE INDEX IF NOT EXISTS idx_audit_logs_device_events 
ON audit_logs (event_type, created_at DESC) 
WHERE event_type LIKE 'device_%';
