//! Guarantees `frontend_edge/dist` exists before this crate is compiled.
//!
//! `src/lib.rs` embeds that directory with `include_dir!`, which is evaluated
//! at compile time and fails outright when the directory is absent. The
//! directory is a build product of `frontend_edge` and is gitignored, so it
//! never exists in a clean checkout — which means every `cargo build`,
//! `cargo test` and `cargo clippy --all-targets` touching this crate failed
//! before it started.
//!
//! CI papered over this with `mkdir -p /builds/<org>/<repo>/edge/../frontend_edge/dist`.
//! That hardcoded one runner's checkout path, and it produced an *empty*
//! embedding — a binary that compiles cleanly and serves 404 for its own UI.
//! Doing it here instead is portable, and it runs for developers too.
//!
//! A real bundle, once `frontend_edge` has been built, is left completely
//! untouched: this only ever creates what is missing.
//!
//! The placeholder is a page that says what happened rather than an empty
//! directory, because the failure it stands in for is silent. Somebody who
//! reaches it should be told to build the frontend, not left looking at a blank
//! screen wondering whether the server is broken.

use std::fs;
use std::path::Path;

fn main() {
    let manifest_dir = std::env::var("CARGO_MANIFEST_DIR")
        .expect("CARGO_MANIFEST_DIR is always set by cargo for a build script");
    let dist = Path::new(&manifest_dir).join("../frontend_edge/dist");

    // Rebuild when the real bundle appears or changes, so a `npm run build` in
    // frontend_edge is picked up without a `cargo clean`.
    println!("cargo:rerun-if-changed={}", dist.display());

    let index = dist.join("index.html");
    if index.exists() {
        return;
    }

    if let Err(e) = fs::create_dir_all(&dist) {
        // A hard failure here is better than the include_dir! error it would
        // otherwise become, which names a macro rather than a missing bundle.
        panic!(
            "could not create the frontend_edge bundle directory at {}: {e}\n\
             This directory is embedded into css-edge at compile time. Either \
             build it with `cd frontend_edge && npm ci && npm run build`, or \
             make the path writable.",
            dist.display()
        );
    }

    let placeholder = "<!doctype html>\n\
        <html lang=\"en\">\n\
        <head><meta charset=\"utf-8\"><title>css-edge: UI not built</title></head>\n\
        <body>\n\
        <h1>The edge UI was not built into this binary</h1>\n\
        <p>This placeholder was generated by <code>edge/build.rs</code> because\n\
        <code>frontend_edge/dist</code> did not exist when <code>css-edge</code> was\n\
        compiled.</p>\n\
        <p>To get the real interface, build it and recompile:</p>\n\
        <pre>cd frontend_edge &amp;&amp; npm ci &amp;&amp; npm run build\n\
        cargo build -p css-edge</pre>\n\
        </body>\n\
        </html>\n";

    if let Err(e) = fs::write(&index, placeholder) {
        panic!("could not write the placeholder at {}: {e}", index.display());
    }
}
